# filepath: /Users/oumoukeirouc./Documents/my-api-dailyquest/config/packages/security.yaml
security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    main:
      # ...autres configurations...
      form_login:
        csrf_parameter: _csrf_token
        csrf_token_id: authenticate
      provider: app_user_provider
      lazy: true

  # Accès aux différentes pages selon les rôles
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }

# Configuration pour l'environnement de test
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
